### ISSUE TITLE
videos not playing

### ISSUE THREAD

**Issue by lukesturgeon** [lukesturgeon/ofx_economicsGlitcher#1]
on another computer, such as Rod's the video wouldn't not play at the beginning (expected) but when you drag a video over it still would not play.

**Comment by peterdavidhudson** [comment]
Oh no! Which one?

**Comment by lukesturgeon** [comment]
He said none of the apps would play any videos that he dragged in. Can you download the zips from release v1.0 and test. I have found  a way to bundle videos inside the app and created a new 180mb app and emailed him. but it means he's only showing 1 app in the exam and we haven't tested it yet!

**Comment by peterdavidhudson** [comment]
Holy moly, I guess he can always just show the raw films anyway if it doesn't work. Sounds stressful! P

**Comment by alberto2000** [comment]
Sorry can’t help on the issue! Worked on my rig the last time I tried...

–––
Riccardo Lardi
MA Design Interactions, Royal College of Arts, London
hello@riccardolardi.com <mailto:hello@riccardolardi.com>
+44 7402 642331

**Comment by lukesturgeon** [comment]
shouldn't be a problem. Just got a call from Rod and he didn't have time to present the glitch. so the pressure was off a little (or on depending on your point of view). I'll be in on friday to look at this and we can all catchup over coffee and see what's left. plan tests etc etc. that's most important now. try to break the things. wrong files. random keystrokes etc

**Comment by lukesturgeon** [comment]
the problem was that any error in the code that appears in xcode, is enough to crash the app running on another machine. we had to fix any errors. in this case, drawing unallocated textures. use ofImage.allocate() to fix
